<?php

namespace Customize\Repository;

use Eccube\Repository\CustomerRepository as OriginalCustomerRepository;
use Customize\Entity\Master\CustomerStatus;
use Eccube\Entity\Master\CustomerStatus as OriginalCustomerStatus;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends OriginalCustomerRepository
{

    public function newCustomer()
    {
        log_info(CustomerStatus::class);
        log_info(OriginalCustomerStatus::class);

        $CustomerStatus = $this->getEntityManager()
            ->find(CustomerStatus::parentClassName(), CustomerStatus::UNAUTHORIZE);

        $Customer = new \Eccube\Entity\Customer();
        $Customer
            ->setStatus($CustomerStatus);

        return $Customer;
    }

}